version: "3.7"

# podman-compose -f ./compose.yml up -d
# java -jar ./build/libs/spring-security-api-1.0.0.jar

services:
  postgres:
    image: docker.io/library/postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spring
    ports:
      - "5432:5432"
